package org.emg.cines_cinex.base;

// Generated 17-feb-2014 15:52:26 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;


/**
 * Cine generated by hbm2java
 */

public class Cine implements java.io.Serializable {

	private Integer id;
	private String ciudad;
	private String nombre;
	private Set<Sala> salas = new HashSet<Sala>(0);


	public Cine() {
	}

	public Cine(String ciudad, String nombre) {
		this.ciudad = ciudad;
		this.nombre = nombre;
	}

	public Cine(String ciudad, String nombre, Set<Sala> salas) {
		this.ciudad = ciudad;
		this.nombre = nombre;
		this.salas = salas;
	}


	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}


	public String getCiudad() {
		return this.ciudad;
	}

	public void setCiudad(String ciudad) {
		this.ciudad = ciudad;
	}

	
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	
	public Set<Sala> getSalas() {
		return this.salas;
	}

	public void setSalas(Set<Sala> salas) {
		this.salas = salas;
	}

}
