package org.emg.cines_cinex.base;

// Generated 17-feb-2014 15:52:26 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;


/**
 * Pelicula generated by hbm2java
 */

public class Pelicula implements java.io.Serializable {

	private Integer id;
	private String titulo;
	private String director;
	private String productora;
	private Set<Sala> salas = new HashSet<Sala>(0);

	public Pelicula() {
	}

	public Pelicula(String titulo, String director, String productora,
			Set<Sala> salas) {
		this.titulo = titulo;
		this.director = director;
		this.productora = productora;
		this.salas = salas;
	}

	
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	
	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}


	public String getDirector() {
		return this.director;
	}

	public void setDirector(String director) {
		this.director = director;
	}

	
	public String getProductora() {
		return this.productora;
	}

	public void setProductora(String productora) {
		this.productora = productora;
	}

	
	public Set<Sala> getSalas() {
		return this.salas;
	}

	public void setSalas(Set<Sala> salas) {
		this.salas = salas;
	}
	@Override
	public String toString() {
		return titulo;
	}
}
