package org.emg.cines_cinex.base;

// Generated 17-feb-2014 15:52:26 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;


/**
 * Sala generated by hbm2java
 */

public class Sala implements java.io.Serializable {

	private Integer id;
	private Pelicula pelicula;
	private String gestor;
	private Integer butacas;
	private Set<Cine> cines = new HashSet<Cine>(0);

	public Sala() {
	}

	public Sala(Pelicula pelicula, String gestor, Integer butacas,
			Set<Cine> cines) {
		this.pelicula = pelicula;
		this.gestor = gestor;
		this.butacas = butacas;
		this.cines = cines;
	}

	
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	
	public Pelicula getPelicula() {
		return this.pelicula;
	}

	public void setPelicula(Pelicula pelicula) {
		this.pelicula = pelicula;
	}


	public String getGestor() {
		return this.gestor;
	}

	public void setGestor(String gestor) {
		this.gestor = gestor;
	}


	public Integer getButacas() {
		return this.butacas;
	}

	public void setButacas(Integer butacas) {
		this.butacas = butacas;
	}

	public Set<Cine> getCines() {
		return this.cines;
	}

	public void setCines(Set<Cine> cines) {
		this.cines = cines;
	}
	
	@Override
	public String toString() {
		return gestor;
	}

}
